spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PWD}
server.port=5000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
teste.varivael.ambiente=${TESTEVARIAVELAMBIENTE}